# Generated by Django 5.0.6 on 2024-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('documento', models.CharField(max_length=20)),
                ('cantTokens', models.IntegerField(default=0)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
