# Generated by Django 5.0.6 on 2024-06-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cantTokens',
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipousuario',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
