# Generated by Django 5.0.6 on 2024-06-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0002_remove_alumno_canttokens_alumno_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cantTokens',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
