# Generated by Django 5.0.7 on 2024-07-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0003_alumno_canttokens_alter_alumno_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('tipousuario', models.CharField(max_length=15)),
                ('cantTokens', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
