# Generated by Django 5.0.7 on 2024-07-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0004_usuario_delete_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idAlumno',
            new_name='idUsuario',
        ),
    ]
