# Generated by Django 5.0.7 on 2024-07-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0005_rename_idalumno_usuario_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
